'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'zh' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// 翻译字典
const translations = {
  zh: {
    // Hero 区域
    'hero.title.line1': '用 AI 为你的宠物',
    'hero.title.line2': '生成超萌 Q 版头像',
    'hero.subtitle': '只需输入品种，几秒钟即可获得 4 张专属 Q 版头像，完美适配社交媒体、头像、周边制作',
    'hero.tag.ai': 'AI 智能生成',
    'hero.tag.fast': '秒级出图',
    'hero.tag.hd': '高清无水印',
    'hero.cta': '立即开始生成',
    'hero.pricing': '根据风格消耗 1-3 积分，生成 4 张 1024x1024 高清图片',
    'hero.welcomeBack': '欢迎回来',
    'hero.freeTrial': '🎁 新用户免费获得 3 个积分！立即体验 AI 生成',

    // Features 卖点
    'features.title': '为什么选择我们',
    'features.subtitle': '专业 AI 技术，极致用户体验',
    'features.ai.title': '🎨 AI 智能生成',
    'features.ai.desc': '基于先进的 AI 模型，自动理解宠物特征，生成独一无二的 Q 版形象',
    'features.fast.title': '⚡ 秒级出图',
    'features.fast.desc': '无需等待，输入品种后几秒钟即可获得 4 张精美头像',
    'features.hd.title': '💎 高清无水印',
    'features.hd.desc': '1024x1024 超高清分辨率，无水印，支持商业使用，永久下载',

    // 如何使用
    'howto.title': '🚀 如何使用',
    'howto.subtitle': '3 步即可获得专属 Q 版宠物头像',
    'howto.step1.title': '注册并获得免费积分',
    'howto.step1.desc': '新用户注册即可获得 3 个免费积分，立即体验 AI 生成',
    'howto.step2.title': '选择风格并生成',
    'howto.step2.desc': '输入宠物品种，选择风格（萌系1积分、贴纸2积分、日系3积分），一键生成',
    'howto.step3.title': '获得高清图片',
    'howto.step3.desc': '立即获得 4 张 1024x1024 高清无水印图片，永久保存和下载',
    'howto.step4.title': '查看历史记录',
    'howto.step4.desc': '在历史记录页面随时查看和下载你的所有作品',

    // Examples 示例
    'examples.title': '精美示例作品',
    'examples.subtitle': '看看其他用户生成的可爱头像',
    'examples.sample': 'Q 版头像示例',
    'examples.hint': '以上为真实宠物照片，生成后将获得可爱的 Q 版头像',
    'examples.tryNow': '立即生成我的宠物头像',
    'examples.viewMore': '查看更多示例',

    // Credit System Info (积分系统说明)
    'creditsystem.title': '积分系统说明',
    'creditsystem.subtitle': '不同风格消耗不同积分，生成即高清',
    'creditsystem.standard': '标准',
    'creditsystem.advanced': '高级',
    'creditsystem.professional': '专业',
    'creditsystem.cute.desc': '圆润可爱，大眼睛大头',
    'creditsystem.chibi.desc': '二头身，精致贴纸风格',
    'creditsystem.kawaii.desc': '日式卡哇伊，最高质量',
    'creditsystem.feature1': '4 张高清图片',
    'creditsystem.feature2': '1024x1024 分辨率',
    'creditsystem.feature3': '无水印，可商用',
    'creditsystem.feature4': '永久下载',
    'creditsystem.cute.feature1': '快速生成，性价比高',
    'creditsystem.cute.feature2': '圆润可爱风格',
    'creditsystem.cute.feature3': '适合个人使用',
    'creditsystem.cute.feature4': '社交媒体分享',
    'creditsystem.chibi.feature1': '精致贴纸效果',
    'creditsystem.chibi.feature2': '细节优化处理',
    'creditsystem.chibi.feature3': '支持商业用途',
    'creditsystem.chibi.feature4': '适合品牌宣传',
    'creditsystem.kawaii.feature1': '艺术级绘制质量',
    'creditsystem.kawaii.feature2': '专业商用授权',
    'creditsystem.kawaii.feature3': '日系美学巅峰',
    'creditsystem.kawaii.feature4': '适合高端设计',
    'creditsystem.allInclude.title': '✨ 所有套餐均包含',
    'creditsystem.allInclude.images': '4 张图片',
    'creditsystem.allInclude.imagesDesc': '每次生成',
    'creditsystem.allInclude.resolution': '高清画质',
    'creditsystem.allInclude.resolutionDesc': '1024x1024',
    'creditsystem.allInclude.watermark': '无水印',
    'creditsystem.allInclude.watermarkDesc': '纯净图片',
    'creditsystem.allInclude.download': '永久下载',
    'creditsystem.allInclude.downloadDesc': '随时保存',
    'creditsystem.newuser.title': '新用户福利',
    'creditsystem.newuser.desc': '注册即可获得 3 个免费积分，体验 AI 生成的魅力！',
    'creditsystem.buyCredits': '购买更多积分',

    // 首页
    'home.title': '🐾 宠物 Q 版头像生成器',
    'home.subtitle': '输入你的宠物品种，生成超可爱的 Q 版头像',
    'home.tip': '💡 目前支持狗狗和猫咪品种，效果最佳',
    'home.breedLabel': '宠物品种',
    'home.breedPlaceholder': '例如：金毛、柯基、柴犬、布偶猫...',
    'home.breedTip': '常见品种：',
    'home.styleLabel': '选择 Q 版风格',
    'home.style.cute': '软萌大头',
    'home.style.cute.desc': '圆润可爱，大眼睛大头',
    'home.style.chibi': 'Q 版贴纸',
    'home.style.chibi.desc': '二头身，贴纸风格',
    'home.style.kawaii': '日系萌系',
    'home.style.kawaii.desc': '日式卡哇伊风格',
    'home.submit': '🎨 生成 Q 版头像',
    'home.creditInfo': '生成将消耗相应积分，生成 4 张 1024x1024 高清图片',
    'home.loginRequired': '需要登录才能生成',
    'home.alert.breed': '请输入宠物品种',

    // 生成页面
    'generate.title': '为你生成超可爱的 Q 版头像',
    'generate.generating': 'AI 正在生成中...',
    'generate.wait': '请稍候，大约需要几秒钟',
    'generate.progress': '生成进度',
    'generate.tip': 'AI 正在为你创作独特的作品，请稍候...',
    'generate.step.preparing': '准备生成...',
    'generate.step.requesting': '正在连接 AI...',
    'generate.step.generating': '正在生成第 {current}/{total} 张...',
    'generate.step.finalizing': '正在完成...',
    'generate.step.complete': '生成完成！',
    'generate.preview': '✨ 免费预览（2 张）',
    'generate.free': '免费',
    'generate.lowQuality': '低质量预览',
    'generate.locked': '🔒 高清原图（2 张）',
    'generate.unlock': '需解锁',
    'generate.locked.icon': '🔒',
    'generate.locked.text': '需要解锁',
    'generate.previewNote': '* 以上为低分辨率预览图，仅供参考',
    'generate.unlockTitle': '解锁全部 4 张高清原图',
    'generate.unlockDesc': '1024x1024 高分辨率 · 无水印 · 可商用 · 永久下载',
    'generate.price': '1 积分',
    'generate.oneTime': '一次性使用',
    'generate.unlockBtn': '💳 立即解锁',
    'generate.back': '← 返回首页，重新生成',
    'generate.generateMore': '生成更多头像',
    'generate.error.title': '生成失败',
    'generate.error.tips': '可能的原因：网络问题、AI 服务暂时不可用、或者品种输入不正确',
    'generate.error.retry': '重试',
    'generate.error.back': '返回首页',
    'generate.comparison.title': '免费预览 vs 高清原图对比',
    'generate.comparison.tip': '提示：',
    'generate.comparison.desc': '高清原图分辨率是预览图的 4 倍，细节更丰富，适合打印、制作周边或商业使用',
    'generate.comparison.free': '✓ 免费预览',
    'generate.comparison.freeRes': '• 分辨率：512x512',
    'generate.comparison.freeSuit': '• 适合：在线预览',
    'generate.comparison.freeQuality': '• 质量：中等',
    'generate.comparison.freeLimit': '• 限制：仅 2 张',
    'generate.comparison.hd': '⭐ 高清原图 - 1 积分',
    'generate.comparison.hdRes': '• 分辨率：1024x1024 <strong>(4倍清晰)</strong>',
    'generate.comparison.hdSuit': '• 适合：打印、商用、头像',
    'generate.comparison.hdQuality': '• 质量：超高清无损',
    'generate.comparison.hdCount': '• 数量：全部 4 张',
    'generate.comparison.hdExtra': '• 无水印 + 永久下载',

    // 支付页面
    'checkout.title': '正在跳转支付...',
    'checkout.wait': '请稍候',
    'checkout.error': '创建支付失败',
    'checkout.back': '返回重试',

    // 成功页面
    'success.verifying': '验证支付中...',
    'success.wait': '请稍候',
    'success.error': '⚠️',
    'success.errorTitle': '验证失败',
    'success.backHome': '返回首页',
    'success.title': '🎉',
    'success.successTitle': '支付成功！',
    'success.thanks': '感谢您的购买！已支付 $',
    'success.images': '✨ 您的高清原图（4 张）',
    'success.downloadAll': '📥 下载全部',
    'success.download': '下载图 ',
    'success.tip': '💡 <strong>提示：</strong>这些图片为 1024x1024 高分辨率，无水印，可用于商业用途。您可以随时重新访问此页面下载（请保存此页面链接）。',
    'success.home': '🏠 返回首页',
    'success.more': '✨ 生成更多头像',
    'success.alt.hd': '高清图 ',
    'success.alt.preview': '预览图 ',
    'success.alt.locked': '锁定图 ',

    // 品种名称
    'breed.shibaInu': '柴犬',
    'breed.goldenRetriever': '金毛',
    'breed.husky': '哈士奇',
    'breed.corgi': '柯基',
    'breed.poodle': '泰迪',
    'breed.borderCollie': '边牧',
    'breed.samoyed': '萨摩耶',
    'breed.labrador': '拉布拉多',
    'breed.ragdoll': '布偶猫',
    'breed.britishShorthair': '英短',
    'breed.americanShorthair': '美短',
    'breed.siamese': '暹罗猫',
    'breed.persian': '波斯猫',
    'breed.maineCoon': '缅因猫',
    'breed.orangeTabby': '橘猫',

    // 导航栏
    'nav.history': '历史记录',
    'nav.welcome': '欢迎使用',
    'nav.credits': '积分',

    // 积分系统
    'credits.title': '购买积分',
    'credits.subtitle': '使用积分解锁高清图片，无需每次付费',
    'credits.currentBalance': '当前余额',
    'credits.balanceDesc': '你可以使用积分生成高清图',
    'credits.credits': '积分',
    'credits.packages': '选择套餐',
    'credits.popular': '🔥 最受欢迎',
    'credits.perCredit': '/积分',
    'credits.feature1': '可生成高清图',
    'credits.feature2': '永不过期',
    'credits.feature3': '1024x1024 高清',
    'credits.buyNow': '立即购买',
    'credits.purchasing': '处理中...',
    'credits.loginRequired': '请先登录',
    'credits.loginRequiredDesc': '你需要登录后才能购买积分',
    'credits.purchaseError': '购买失败，请重试',
    'credits.faq.title': '常见问题',
    'credits.faq.q1': '积分如何使用？',
    'credits.faq.a1': '生成宠物头像预览图后，使用 1 个积分即可解锁全部 4 张 1024x1024 高清无水印图片。',
    'credits.faq.q2': '积分会过期吗？',
    'credits.faq.a2': '不会！积分永不过期，随时可用。',
    'credits.faq.q3': '支持哪些支付方式？',
    'credits.faq.a3': '我们使用 Stripe 支付，支持信用卡、借记卡等多种支付方式，安全可靠。',
    'credits.success.title': '购买成功！',
    'credits.success.description': '积分已添加到你的账户，现在可以开始生成高清宠物头像了！',
    'credits.success.credited': '积分已到账',
    'credits.success.newBalance': '当前余额',
    'credits.success.orderId': '订单号',
    'credits.success.generate': '开始生成头像',
    'credits.success.viewHistory': '查看历史记录',

    // 生成页面 - 积分相关
    'generate.loginRequired': '请先登录',
    'generate.insufficientCredits': '积分不足，请先购买积分',
    'generate.cost': '需要',
    'generate.credit': '积分',
    'generate.yourBalance': '你的余额',
    'generate.unlocking': '解锁中...',
    'generate.loginToUnlock': '登录后解锁',
    'generate.buyCredits': '购买积分',
    'generate.goToCredits': '→ 前往购买积分',
    'generate.unlockSuccess': '解锁成功！',
    'generate.unlockError': '解锁失败，请重试',
    'generate.unlocked': '已解锁！',
    'generate.unlockedDesc': '你现在可以下载全部 4 张高清无水印图片',
    'generate.creditsRemaining': '剩余',
    'generate.creditsUsed': '已使用',
    'generate.viewInHistory': '在历史记录中查看',
    'generate.viewHistory': '查看历史记录',
    'generate.success.title': '生成成功！',
    'generate.success.desc': '你的宠物 Q 版头像已生成，所有图片均为 1024x1024 高清无水印',
    'generate.hdImages': '高清图片',
    'generate.images': '张',
    'generate.download': '下载图片',
    'generate.usage.title': '使用说明',
    'generate.usage.commercial': '所有图片可商用，无需署名',
    'generate.usage.noWatermark': '高清无水印，1024x1024 分辨率',
    'generate.usage.download': '支持永久下载，可用于头像、打印、周边',
    'generate.error.unauthorized': '需要登录',
    'generate.error.loginTip': '请先登录后再生成图片',
    'generate.error.creditsTip': '你需要更多积分来生成这个风格的图片',

    // 历史记录页面
    'history.title': '我的生成记录',
    'history.subtitle': '查看你之前生成的所有 Q 版头像',
    'history.totalGenerations': '总生成数',
    'history.paid': '已付费',
    'history.images': '张图片',
    'history.hdImages': '张高清图',
    'history.view': '查看',
    'history.download': '下载',
    'history.downloadAll': '下载全部高清图',
    'history.noHdImages': '没有高清图片可下载',
    'history.downloadError': '下载失败，请重试',
    'history.imageExpired': '图片已过期',
    'history.loadError': '加载失败',
    'history.loadTimeout': '加载超时，请刷新重试',
    'history.loadUnauthorized': '未授权，请重新登录',
    'history.loadServerError': '服务器错误，请稍后重试',
    'history.empty.title': '还没有生成记录',
    'history.empty.description': '开始生成你的第一个 Q 版宠物头像吧！',
    'history.empty.cta': '立即开始生成',
    'history.clearAll': '清除历史',
    'history.clearing': '清除中...',
    'history.confirmClear': '确认清除',
    'history.clearSuccess': '历史记录已清除',
    'history.clearError': '清除失败，请重试',
    'history.clearTimeout': '请求超时，请检查网络连接后重试',
    'history.clearUnauthorized': '未授权，请重新登录',
    'history.clearServerError': '服务器错误，请稍后重试',
    'history.clearNetworkError': '网络错误，请检查网络连接',
    'history.clearConfirm.title': '确认清除历史记录？',
    'history.clearConfirm.description': '此操作将删除所有历史记录，且无法恢复。',
    'history.clearConfirm.warning': '⚠️ 即将删除所有记录',

    // 社交分享
    'share.title': '分享你的创作',
    'share.description': '分享到社交媒体，让更多人看到你可爱的宠物头像！',
    'share.text': '我用 AI 给我的宠物生成了超萌的 Q 版头像！快来试试吧！',
    'share.defaultText': '用 AI 为你的宠物生成超可爱的 Q 版头像！免费试用！',
    'share.copyLink': '复制链接',
    'share.copied': '已复制',
    'share.download': '下载图片',
    'share.instagram': 'Instagram',
    'share.wechatHint': '💡 提示：复制链接后可以分享到微信、QQ 等社交平台',
    'share.mobileHint': '💡 提示：点击 Instagram 按钮可直接分享图片到 Instagram、微信等应用',

    // 认证
    'auth.signIn': '登录',
    'auth.signUp': '注册',

    // 通用
    'common.loading': '加载中...',
    'common.cancel': '取消',
    'common.close': '关闭',
  },
  en: {
    // Hero Section
    'hero.title.line1': 'Generate Adorable',
    'hero.title.line2': 'Q-version Pet Avatars with AI',
    'hero.subtitle': 'Just enter the breed, get 4 exclusive Q-version avatars in seconds, perfect for social media, profiles, and merchandise',
    'hero.tag.ai': 'AI Powered',
    'hero.tag.fast': 'Instant Results',
    'hero.tag.hd': 'HD & No Watermark',
    'hero.cta': 'Start Generating Now',
    'hero.pricing': 'Consume 1-3 credits based on style, generate 4 1024x1024 HD images',
    'hero.welcomeBack': 'Welcome back',
    'hero.freeTrial': '🎁 New users get 3 FREE credits! Try AI generation now',

    // Features
    'features.title': 'Why Choose Us',
    'features.subtitle': 'Professional AI technology, ultimate user experience',
    'features.ai.title': '🎨 AI Smart Generation',
    'features.ai.desc': 'Based on advanced AI models, automatically understands pet features to create unique Q-version images',
    'features.fast.title': '⚡ Instant Results',
    'features.fast.desc': 'No waiting required, get 4 beautiful avatars in seconds after entering breed',
    'features.hd.title': '💎 HD No Watermark',
    'features.hd.desc': '1024x1024 ultra-high resolution, no watermark, commercial use supported, permanent download',

    // How to Use
    'howto.title': '🚀 How to Use',
    'howto.subtitle': 'Get your exclusive Q-version pet avatar in 3 steps',
    'howto.step1.title': 'Sign up & Get Free Credits',
    'howto.step1.desc': 'New users get 3 free credits to experience AI generation instantly',
    'howto.step2.title': 'Choose Style & Generate',
    'howto.step2.desc': 'Enter pet breed, select style (Cute 1 credit, Chibi 2 credits, Kawaii 3 credits), generate instantly',
    'howto.step3.title': 'Get HD Images',
    'howto.step3.desc': 'Instantly receive 4 HD 1024x1024 watermark-free images, save and download forever',
    'howto.step4.title': 'View History',
    'howto.step4.desc': 'Access and download all your creations anytime from the history page',

    // Examples
    'examples.title': 'Beautiful Examples',
    'examples.subtitle': 'See cute avatars created by other users',
    'examples.sample': 'Q-version Avatar Sample',
    'examples.hint': 'These are real pet photos, you will get cute Q-version avatars after generation',
    'examples.tryNow': 'Generate My Pet Avatar Now',
    'examples.viewMore': 'View More Examples',

    // Credit System Info
    'creditsystem.title': 'Credit System Guide',
    'creditsystem.subtitle': 'Different styles consume different credits, instant HD generation',
    'creditsystem.standard': 'Standard',
    'creditsystem.advanced': 'Advanced',
    'creditsystem.professional': 'Professional',
    'creditsystem.cute.desc': 'Round and adorable, big eyes and head',
    'creditsystem.chibi.desc': '2-head-tall, refined sticker style',
    'creditsystem.kawaii.desc': 'Japanese kawaii, highest quality',
    'creditsystem.feature1': '4 HD images',
    'creditsystem.feature2': '1024x1024 resolution',
    'creditsystem.feature3': 'No watermark, commercial use',
    'creditsystem.feature4': 'Permanent download',
    'creditsystem.cute.feature1': 'Fast generation, great value',
    'creditsystem.cute.feature2': 'Round and adorable style',
    'creditsystem.cute.feature3': 'Perfect for personal use',
    'creditsystem.cute.feature4': 'Social media ready',
    'creditsystem.chibi.feature1': 'Refined sticker effect',
    'creditsystem.chibi.feature2': 'Detail optimization',
    'creditsystem.chibi.feature3': 'Commercial use supported',
    'creditsystem.chibi.feature4': 'Brand promotion ready',
    'creditsystem.kawaii.feature1': 'Artistic-grade quality',
    'creditsystem.kawaii.feature2': 'Professional license',
    'creditsystem.kawaii.feature3': 'Peak Japanese aesthetics',
    'creditsystem.kawaii.feature4': 'High-end design ready',
    'creditsystem.allInclude.title': '✨ All Packages Include',
    'creditsystem.allInclude.images': '4 Images',
    'creditsystem.allInclude.imagesDesc': 'Per generation',
    'creditsystem.allInclude.resolution': 'HD Quality',
    'creditsystem.allInclude.resolutionDesc': '1024x1024',
    'creditsystem.allInclude.watermark': 'No Watermark',
    'creditsystem.allInclude.watermarkDesc': 'Clean images',
    'creditsystem.allInclude.download': 'Permanent Download',
    'creditsystem.allInclude.downloadDesc': 'Save anytime',
    'creditsystem.newuser.title': 'New User Benefits',
    'creditsystem.newuser.desc': 'Get 3 free credits upon registration and experience the magic of AI generation!',
    'creditsystem.buyCredits': 'Buy More Credits',

    // Homepage
    'home.title': '🐾 Pet Q-version Avatar Generator',
    'home.subtitle': 'Enter your pet breed to generate super cute Q-version avatars',
    'home.tip': '💡 Currently supports dog and cat breeds for best results',
    'home.breedLabel': 'Pet Breed',
    'home.breedPlaceholder': 'e.g., Golden Retriever, Corgi, Shiba Inu, Ragdoll Cat...',
    'home.breedTip': 'Popular breeds:',
    'home.styleLabel': 'Choose Q-version Style',
    'home.style.cute': 'Soft & Cute',
    'home.style.cute.desc': 'Round and adorable, big eyes and head',
    'home.style.chibi': 'Chibi Sticker',
    'home.style.chibi.desc': '2-head-tall, sticker style',
    'home.style.kawaii': 'Kawaii Style',
    'home.style.kawaii.desc': 'Japanese kawaii style',
    'home.submit': '🎨 Generate Avatar',
    'home.creditInfo': 'Generation will consume corresponding credits, generating 4 1024x1024 HD images',
    'home.loginRequired': 'Login required to generate',
    'home.alert.breed': 'Please enter pet breed',

    // Generate page
    'generate.title': 'Generating super cute Q-version avatars for you',
    'generate.generating': 'AI is generating...',
    'generate.wait': 'Please wait, it will take a few seconds',
    'generate.progress': 'Generation Progress',
    'generate.tip': 'AI is creating unique artwork for you, please wait...',
    'generate.step.preparing': 'Preparing to generate...',
    'generate.step.requesting': 'Connecting to AI...',
    'generate.step.generating': 'Generating image {current}/{total}...',
    'generate.step.finalizing': 'Finalizing...',
    'generate.step.complete': 'Generation complete!',
    'generate.preview': '✨ Free Preview (2 images)',
    'generate.free': 'Free',
    'generate.lowQuality': 'Low Quality Preview',
    'generate.locked': '🔒 HD Originals (2 images)',
    'generate.unlock': 'Locked',
    'generate.locked.icon': '🔒',
    'generate.locked.text': 'Need Unlock',
    'generate.previewNote': '* Low-resolution preview images for reference only',
    'generate.unlockTitle': 'Unlock All 4 HD Original Images',
    'generate.unlockDesc': '1024x1024 High Resolution · No Watermark · Commercial Use · Permanent Download',
    'generate.price': '1 Credit',
    'generate.oneTime': 'One-time use',
    'generate.unlockBtn': '💳 Unlock Now',
    'generate.back': '← Back to home, regenerate',
    'generate.generateMore': 'Generate More',
    'generate.error.title': 'Generation Failed',
    'generate.error.tips': 'Possible reasons: Network issues, AI service temporarily unavailable, or incorrect breed input',
    'generate.error.retry': 'Retry',
    'generate.error.back': 'Back to Home',
    'generate.comparison.title': 'Free Preview vs HD Original Comparison',
    'generate.comparison.tip': 'Tip:',
    'generate.comparison.desc': 'HD originals have 4x the resolution of previews, with richer details, suitable for printing, merchandise, or commercial use',
    'generate.comparison.free': '✓ Free Preview',
    'generate.comparison.freeRes': '• Resolution: 512x512',
    'generate.comparison.freeSuit': '• Best for: Online preview',
    'generate.comparison.freeQuality': '• Quality: Medium',
    'generate.comparison.freeLimit': '• Limit: Only 2 images',
    'generate.comparison.hd': '⭐ HD Original - 1 Credit',
    'generate.comparison.hdRes': '• Resolution: 1024x1024 <strong>(4x clearer)</strong>',
    'generate.comparison.hdSuit': '• Best for: Printing, commercial use, avatar',
    'generate.comparison.hdQuality': '• Quality: Ultra HD lossless',
    'generate.comparison.hdCount': '• Count: All 4 images',
    'generate.comparison.hdExtra': '• No watermark + Permanent download',

    // Checkout page
    'checkout.title': 'Redirecting to payment...',
    'checkout.wait': 'Please wait',
    'checkout.error': 'Failed to create payment',
    'checkout.back': 'Back to retry',

    // Success page
    'success.verifying': 'Verifying payment...',
    'success.wait': 'Please wait',
    'success.error': '⚠️',
    'success.errorTitle': 'Verification Failed',
    'success.backHome': 'Back to Home',
    'success.title': '🎉',
    'success.successTitle': 'Payment Successful!',
    'success.thanks': 'Thank you for your purchase! Paid $',
    'success.images': '✨ Your HD Original Images (4 images)',
    'success.downloadAll': '📥 Download All',
    'success.download': 'Download ',
    'success.tip': '💡 <strong>Tip:</strong> These images are 1024x1024 high resolution, no watermark, available for commercial use. You can revisit this page anytime to download (please save this page link).',
    'success.home': '🏠 Back to Home',
    'success.more': '✨ Generate More Avatars',
    'success.alt.hd': 'HD Image ',
    'success.alt.preview': 'Preview ',
    'success.alt.locked': 'Locked ',

    // Breed names
    'breed.shibaInu': 'Shiba Inu',
    'breed.goldenRetriever': 'Golden Retriever',
    'breed.husky': 'Husky',
    'breed.corgi': 'Corgi',
    'breed.poodle': 'Poodle',
    'breed.borderCollie': 'Border Collie',
    'breed.samoyed': 'Samoyed',
    'breed.labrador': 'Labrador',
    'breed.ragdoll': 'Ragdoll',
    'breed.britishShorthair': 'British Shorthair',
    'breed.americanShorthair': 'American Shorthair',
    'breed.siamese': 'Siamese',
    'breed.persian': 'Persian',
    'breed.maineCoon': 'Maine Coon',
    'breed.orangeTabby': 'Orange Tabby',

    // Navigation
    'nav.history': 'History',
    'nav.welcome': 'Welcome',
    'nav.credits': 'Credits',

    // Credits System
    'credits.title': 'Buy Credits',
    'credits.subtitle': 'Use credits to unlock HD images, no payment needed each time',
    'credits.currentBalance': 'Current Balance',
    'credits.balanceDesc': 'You can use credits to generate HD images',
    'credits.credits': 'Credits',
    'credits.packages': 'Choose Package',
    'credits.popular': '🔥 Most Popular',
    'credits.perCredit': '/credit',
    'credits.feature1': 'Generate HD images',
    'credits.feature2': 'Never expire',
    'credits.feature3': '1024x1024 HD',
    'credits.buyNow': 'Buy Now',
    'credits.purchasing': 'Processing...',
    'credits.loginRequired': 'Please sign in first',
    'credits.loginRequiredDesc': 'You need to sign in to purchase credits',
    'credits.purchaseError': 'Purchase failed, please retry',
    'credits.faq.title': 'FAQ',
    'credits.faq.q1': 'How to use credits?',
    'credits.faq.a1': 'After generating pet avatar previews, use 1 credit to unlock all 4 HD 1024x1024 watermark-free images.',
    'credits.faq.q2': 'Do credits expire?',
    'credits.faq.a2': 'No! Credits never expire and can be used anytime.',
    'credits.faq.q3': 'What payment methods are supported?',
    'credits.faq.a3': 'We use Stripe payment, supporting credit cards, debit cards and more, safe and reliable.',
    'credits.success.title': 'Purchase Successful!',
    'credits.success.description': 'Credits have been added to your account, you can now start generating HD pet avatars!',
    'credits.success.credited': 'Credits Added',
    'credits.success.newBalance': 'Current Balance',
    'credits.success.orderId': 'Order ID',
    'credits.success.generate': 'Start Generating',
    'credits.success.viewHistory': 'View History',

    // Generate page - Credits related
    'generate.loginRequired': 'Please sign in first',
    'generate.insufficientCredits': 'Insufficient credits, please buy credits first',
    'generate.cost': 'Cost',
    'generate.credit': 'credit',
    'generate.yourBalance': 'Your Balance',
    'generate.unlocking': 'Unlocking...',
    'generate.loginToUnlock': 'Sign in to unlock',
    'generate.buyCredits': 'Buy Credits',
    'generate.goToCredits': '→ Go to buy credits',
    'generate.unlockSuccess': 'Unlock successful!',
    'generate.unlockError': 'Unlock failed, please retry',
    'generate.unlocked': 'Unlocked!',
    'generate.unlockedDesc': 'You can now download all 4 HD watermark-free images',
    'generate.creditsRemaining': 'Remaining',
    'generate.creditsUsed': 'Used',
    'generate.viewInHistory': 'View in history',
    'generate.viewHistory': 'View History',
    'generate.success.title': 'Generation Successful!',
    'generate.success.desc': 'Your pet Q-version avatar has been generated. All images are 1024x1024 HD without watermark',
    'generate.hdImages': 'HD Images',
    'generate.images': 'images',
    'generate.download': 'Download Image',
    'generate.usage.title': 'Usage Instructions',
    'generate.usage.commercial': 'All images are commercial-use, no attribution required',
    'generate.usage.noWatermark': 'HD without watermark, 1024x1024 resolution',
    'generate.usage.download': 'Permanent download, suitable for avatars, printing, merchandise',
    'generate.error.unauthorized': 'Login Required',
    'generate.error.loginTip': 'Please log in first to generate images',
    'generate.error.creditsTip': 'You need more credits to generate this style',

    // History Page
    'history.title': 'My Generation History',
    'history.subtitle': 'View all your previously generated Q-version avatars',
    'history.totalGenerations': 'Total Generations',
    'history.paid': 'Paid',
    'history.images': 'images',
    'history.hdImages': 'HD images',
    'history.view': 'View',
    'history.download': 'Download',
    'history.downloadAll': 'Download All HD Images',
    'history.noHdImages': 'No HD images available for download',
    'history.downloadError': 'Download failed, please try again',
    'history.imageExpired': 'Image Expired',
    'history.loadError': 'Failed to load',
    'history.loadTimeout': 'Load timeout, please refresh and try again',
    'history.loadUnauthorized': 'Unauthorized, please log in again',
    'history.loadServerError': 'Server error, please try again later',
    'history.empty.title': 'No Generations Yet',
    'history.empty.description': 'Start generating your first Q-version pet avatar!',
    'history.empty.cta': 'Start Generating',
    'history.clearAll': 'Clear History',
    'history.clearing': 'Clearing...',
    'history.confirmClear': 'Confirm Clear',
    'history.clearSuccess': 'History cleared successfully',
    'history.clearError': 'Failed to clear history, please try again',
    'history.clearTimeout': 'Request timeout, please check your network connection',
    'history.clearUnauthorized': 'Unauthorized, please log in again',
    'history.clearServerError': 'Server error, please try again later',
    'history.clearNetworkError': 'Network error, please check your connection',
    'history.clearConfirm.title': 'Clear all history?',
    'history.clearConfirm.description': 'This action will delete all history records and cannot be undone.',

    // Social Sharing
    'share.title': 'Share Your Creation',
    'share.description': 'Share on social media to let more people see your cute pet avatar!',
    'share.text': 'I created an adorable Q-version avatar for my pet with AI! Try it now!',
    'share.defaultText': 'Generate super cute Q-version pet avatars with AI! Free trial available!',
    'share.copyLink': 'Copy Link',
    'share.copied': 'Copied',
    'share.download': 'Download',
    'share.instagram': 'Instagram',
    'share.wechatHint': '💡 Tip: Copy the link to share on social platforms',
    'share.mobileHint': '💡 Tip: Click Instagram button to share directly to Instagram and other apps',
    'history.clearConfirm.warning': '⚠️ About to delete all records',

    // Authentication
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',

    // Common
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh')

  // 从 localStorage 加载语言偏好
  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language
    if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
      setLanguageState(savedLang)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['zh']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
